task: y_mort
backbone_name: big_bird
main_window: within48_query
version: without_retrieval
job_id: ${SLURM_JOB_ID}

ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251126_184701-big_bird_13218231_1024_128_15_maskprob_12_5overlap/files/ckpt/epoch=43-step=221716.ckpt
seq_gen:
  tokenizer_path: /scratch/sas10092/ehr-foundation/vocab.json
  seq_length: 1024
  overlap: 0

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/meds_normalized_arrow
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet

dataloader:
  batch_size: 16

logger:
  wandb_api_key: 59b6438e0496b3089f91abef35d31dae69b6c009
  project: MedEHR_Final
  entity: nyuad-cai
  log_dir: /scratch/sas10092/ehr-foundation/models/eval