# seq_length: 512
# overlap: 64
# main_window: within24_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within24_hist_full

# seq_length: 512
# overlap: 64
# main_window: within48_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within48_hist_full


# run this in the morning

seq_length: 512
overlap: 64
main_window: within_stay_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within_stay_hist_full




ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251128_073215-roformer_13218339_1024_128_15_maskprob_12_5overlap/files/ckpt/epoch=65-step=665082.ckpt

seq_gen:
  tokenizer_path: /scratch/sas10092/ehr-foundation/vocab.json
  

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/meds_normalized_arrow
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet
  
embedder:
  pool: mean

client:
  path: /scratch/sas10092/ehr-foundation/data/vectordbs/roformer/mean/











  
  





