# seq_length: 512
# overlap: 64
# main_window: within24_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within24_hist_full

# seq_length: 512
# overlap: 64
# main_window: within48_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within48_hist_full


# run this in the morning

seq_length: 512
overlap: 64
main_window: within_stay_hist_full

# seq_length: 1024
# overlap: 128
# main_window: within_stay_hist_full




ckpt_path:
seq_gen:
  tokenizer_path: 
  

dataset:
  data_path: 
  data_idx_path: 
  
embedder:
  pool: mean

client:
  path: 











  
  





