backbone_name: roformer
version: with_retrieval
job_id: ${SLURM_JOB_ID}
seed: 20

model:
  ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251128_073215-roformer_13218339_1024_128_15_maskprob_12_5overlap/files/ckpt/epoch=65-step=665082.ckpt

retriever:
  ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251128_073215-roformer_13218339_1024_128_15_maskprob_12_5overlap/files/ckpt/epoch=65-step=665082.ckpt
  pooling: mean 
  normalize: True

seq_gen:
  tokenizer_path: /scratch/sas10092/ehr-foundation/vocab.json
  seq_length: 1024
  overlap: 0

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/meds_normalized_arrow
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet
  vectordb_path: /scratch/sas10092/ehr-foundation/data/vectordbs/roformer/mean/within_stay_hist_full_1024_128
  main_window_query: within_stay_query
  task: y_mort_1yr
  top_k: 8

dataloader:
  batch_size: 4


logger:
  wandb_api_key: 59b6438e0496b3089f91abef35d31dae69b6c009
  project: MedEHR_Eval
  entity: nyuad-cai
  log_dir: /scratch/sas10092/ehr-foundation/models/with_retrieval