task: y_los_7
backbone_name: bert
variant: cehrbert
main_window: within24_query
version: baslines
job_id: ${SLURM_JOB_ID}

pooling: cls
use_time: True
use_numeric: False

ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251223_064020-bert_cehrbert_13609308_512_0_15_maskprob_12_5overlap/files/ckpt/epoch=83-step=340704.ckpt
seq_gen:
  tokenizer_path: /scratch/sas10092/ehr-foundation/vocab.json
  seq_length: 512
  overlap: 0

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/meds_normalized_arrow
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet

dataloader:
  batch_size: 64

logger:
  wandb_api_key: 59b6438e0496b3089f91abef35d31dae69b6c009
  project: MedEHR_Eval
  entity: nyuad-cai
  log_dir: /scratch/sas10092/ehr-foundation/models/hparams










  
  





