backbone_name: bert
variant: medbert
version: with_retrieval_final
job_id: ${SLURM_JOB_ID}


model:
  ckpt_path: 



dataset:
  data_path: 
  data_idx_path: 
  tokenizer_path: 
  main_window_query: 
  main_window_history:
  task: 
  seq_length_q: 512
  overlap_q: 0

logger:
  wandb_api_key:
  project: 
  entity: 
  log_dir: 