task: y_los_7
backbone_name: genhpf
main_window: within24_genhpf
version: baslines
job_id: ${SLURM_JOB_ID}
ckpt_path: /scratch/sas10092/ehr-foundation/models/simclr/wandb/run-20251224_094659-genhpf_simclr_genhpf_13612113_511_0_15_maskprob_12_5overlap/files/ckpt/epoch=62-step=21042.ckpt 

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/desc_gen_dataset
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet

dataloader:
  batch_size: 64

logger:
  wandb_api_key: 59b6438e0496b3089f91abef35d31dae69b6c009
  project: MedEHR_Final
  entity: nyuad-cai
  log_dir: /scratch/sas10092/ehr-foundation/models/eval










  
  





