task: y_los_7
backbone_name: bert
variant: hibehrt
main_window: within24_query
version: baslines
job_id: ${SLURM_JOB_ID}

pooling: cls
use_time: False
use_numeric: False


ckpt_path: /scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251223_083520-bert_hibehrt_13609323_512_64_15_maskprob_12_5overlap/files/ckpt/epoch=89-step=405720.ckpt
seq_gen:
  tokenizer_path: /scratch/sas10092/ehr-foundation/vocab.json
  seq_length: 1023
  overlap: 0

dataset:
  data_path: /scratch/sas10092/ehr-foundation/data/meds_normalized_arrow
  data_idx_path: /scratch/sas10092/ehr-foundation/downstream_idx.parquet

dataloader:
  batch_size: 64

logger:
  wandb_api_key: 59b6438e0496b3089f91abef35d31dae69b6c009
  project: MedEHR_Final
  entity: nyuad-cai
  log_dir: /scratch/sas10092/ehr-foundation/models/eval











  
  





